ALTER TABLE users ADD COLUMN offerings INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE curator_submissions ADD COLUMN userId INTEGER;
ALTER TABLE dream_submissions ADD COLUMN userId INTEGER;

CREATE TABLE IF NOT EXISTS offering_ledger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  amount INTEGER NOT NULL,
  reason TEXT NOT NULL,
  createdAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS generated_dreams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  title TEXT NOT NULL,
  prompt TEXT NOT NULL,
  imageUrl TEXT NOT NULL,
  createdAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS specimen_unlocks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  specimenSlug TEXT NOT NULL,
  kind TEXT NOT NULL,
  createdAt INTEGER NOT NULL
);
