export type ArchiveMetadata = {
  medium: string;
  location: string;
  accessionDate: string;
  description: string;
  curatorNote: string;
  prompt: string;
};

const record = (medium: string, location: string, accessionDate: string, description: string, curatorNote: string, prompt: string): ArchiveMetadata => ({ medium, location, accessionDate, description, curatorNote, prompt });

export const archiveMetadata: Record<string, ArchiveMetadata[]> = {
  "technology-nightmares": [
    record("U-matic transfer, signal analysis", "Relay room beneath a closed television station", "January 18, 2024", "The broadcast repeats only when someone is listening closely enough. Between the familiar frames, a second room appears: damp, candlelit, and occupied by a figure facing away from the camera.", "The tape contains no magnetic splice. The room appears six seconds earlier whenever the monitor is viewed by two people at once.", "Lost 1980s analog horror film still of a black television with a mouth of tiny teeth opening in static, wet cables like tendons, dim candlelight, cyan glow, burgundy brown ochre black sickly green, heavy grain, no text."),
    record("35mm surveillance stills, shutter telemetry", "Municipal archive annex, northern England", "February 2, 2024", "Its shutter closes a fraction too late, capturing the person behind the person photographed. No second body appears in the room, but every print contains a damp silhouette at the edge.", "The camera has been unplugged since accession. It still produces one exposure at 03:11 each morning.", "Lost underground horror film still of an obsolete security camera shrine with a wet blinking eye in the lens, cracked plaster, wax and rust, muted burgundy brown black sickly green, analog grain, no text."),
    record("Mechanical keyboard, predictive text log", "Private workstation recovered from a hospice office", "March 29, 2024", "The keyboard suggests a final sentence before the user has begun to feel ill. The prediction changes only after the person touches the space bar.", "The final log contains a sentence addressed to the next owner of the keyboard. The next owner has not yet been identified.", "Analog horror film still of a beige keyboard with bone and tooth keys on a chapel altar, one key depressed, sickly green monitor glow, wet wax and rust, faded 1980s grain, no text."),
    record("Firmware dump, architectural survey", "Maintenance terminal in an abandoned civic building", "April 11, 2024", "A maintenance update installs a floor plan for rooms the building does not contain. The plan grows one corridor each time the software is restarted.", "The terminal reports a successful update even when disconnected from power. Its fan exhales a smell of wet plaster.", "Lost analog horror film still of a maintenance terminal embedded in a breathing wall, impossible floor plan glow, candle beside it, organic architecture, muted burgundy brown ochre black green, no text."),
    record("Bedside monitor, pulse waveform recording", "Unlisted recovery ward", "May 6, 2024", "The screen refreshes in rhythm with a heartbeat located somewhere off-site. The waveform continues after the monitor is removed from the patient room.", "Technicians traced the signal to a locked stairwell beneath the hospital. The stairwell has no lower level on any blueprint.", "Analog horror film still of a hospital monitor with one pulse connected to a rib-like machine shrine and empty chair, cyan glow, candlelight, heavy grain, no text."),
    record("Rotary telephone, audio log", "Weather station at the edge of a drained reservoir", "June 17, 2024", "Every missed call is from the same number, but the voice changes with the weather. During rain, the voice speaks from inside the receiver casing.", "The telephone line ends forty meters from the building. The receiver rings only when clouds cover the moon.", "Lost 1970s horror film still of a rotary telephone on a small altar, cord shaped like a spine, fog from the receiver, rust and wax, muted burgundy brown black green, no text."),
    record("Facial-recognition terminal, incident footage", "Security control room, status sealed", "July 9, 2024", "The system identifies everyone in the room as the person who is missing. The absent subject is not listed in any database, but every camera recognizes them.", "Staff began using masks. The system identified the masks as faces and assigned each one the same date of death.", "Obscure analog horror still of a monitor showing the same empty face for every person, red thread and ritual photographs around it, candlelight, heavy film grain, no text."),
    record("Paper archive cabinet, time-lapse video", "Basement catalogue room of the Veilhouse", "August 21, 2024", "A file opens itself whenever its owner begins to remember deleting it. The drawer is always warm and contains one more page than the previous inspection.", "The accession label is written in the curator's handwriting, although the curator had not yet joined the project.", "Lost analog horror film still of a rusted archive cabinet with one drawer open to a wet eye, church basement, candles, rotting paper and wax, muted colors, no text."),
  ],
  "liminal-spaces": [
    record("Hospital survey photography, corridor measurements", "Closed psychiatric ward, address withheld", "September 4, 2023", "The corridor measured 47 metres yesterday. Today it has no end. Door numbers remain correct until someone attempts to return to the entrance.", "The original measuring tape now records distance in breaths rather than metres.", "Analog horror film still of an endless hospital corridor marked by candles, breathing walls and a distant dark doorway, burgundy brown ochre black sickly green, heavy grain, no text."),
    record("Waiting-room clock, appointment ledger", "Dental clinic abandoned after a power outage", "October 12, 2023", "The clock moves only when someone decides to give up their appointment. Every empty chair faces the same curtained doorway.", "The ledger contains a check-in signature for the archivist dated three years before the room was built.", "Lost 1980s horror film still of an empty waiting room at 4:12 with chairs facing a candlelit chapel curtain, faded wallpaper, cyan haze, no text."),
    record("Elevator control panel, floor photographs", "Residential tower scheduled for demolition", "November 1, 2023", "Every button opens onto a version of the lobby where one person has been removed. The elevator remembers people who never entered it.", "The ground button is made of soft plaster. Pressing it leaves a fingerprint from the other side.", "Analog horror film still of an old elevator opening onto a narrow corridor lined with small mouths, wet stone, candlelight, muted burgundy and sickly green, no text."),
    record("Guest register, lobby photographs", "Hotel between two unlisted addresses", "December 6, 2023", "Guests can check in, but the reservation system cannot find the building. Every room key bears a different street number for the same door.", "The lobby carpet is damp only beneath the feet of guests who intend to leave.", "Lost film still of a hotel lobby with no address, peeling skin-like wallpaper, lone key and silhouette behind reception glass, soft focus, grain, no text."),
    record("Wallpaper sample, architectural mapping", "Former boarding house, coastal district", "January 23, 2024", "A corridor grows one door longer each time you look away. The newest door is always painted the color of the observer's childhood bedroom.", "Removing wallpaper reveals more wallpaper, each layer bearing a different date of inspection.", "Analog horror still of a wallpaper hallway with a hidden door exposed, footprints into blackness, teeth-like trim, candles, faded film grain, no text."),
    record("Stairwell photography, footprint casts", "Municipal stairwell sealed in 1988", "February 14, 2024", "The final step leads back to the first, carrying a different set of footprints. The prints are wet even during drought.", "The stairwell's fire door opens onto the same stairs from above, but the hinges are on the wrong side.", "Dark analog horror film still of a damp stairwell looping into itself, footprints crossing stone, small statue facing wrong way, candlelight, no text."),
    record("One-way glass, room survey", "Public restroom beneath an old cinema", "March 8, 2024", "The window shows the room from the other side of the wall. The reflection enters one second before the person moves.", "A technician covered the glass. The covered surface continued to reflect the room in reverse.", "Lost 1970s horror film still of a cracked tiled restroom with impossible window and pale reflection, wax and sickly green shadows, heavy grain, no text."),
    record("Platform camera, passenger count log", "Disused underground station", "April 3, 2024", "A train arrives empty and leaves with one more passenger than boarded. The added passenger is visible only in the driver's rear mirror.", "The station clock runs backward whenever the train doors close.", "Analog horror film still of an empty underground platform and windowless train in blue-green fog, one wet footprint, candles, faded 1980s texture, no text."),
  ],
  "body-horror": [
    record("Anatomical photography, construction survey", "Unlicensed clinic beneath a demolition site", "May 2, 2024", "The body is not a container. It is a building site with a weather system. The subject's ribs cast shadows shaped like unfinished rooms.", "The subject requested a building permit for their chest cavity. The municipal office approved it without comment.", "Analog horror film still of a torso transformed into a miniature ruin, ribs as scaffolding, candle beneath the sternum, wet flesh and bone, muted burgundy brown black green, no text."),
    record("Thoracic imaging, directional audio", "Listening laboratory, room 3", "June 13, 2024", "An additional cavity behind the sternum produces a low signal when addressed by name. The cavity closes when the subject is alone.", "The recording contains a second listener breathing in perfect time with the technician.", "Lost medical horror film still of a profile torso with a dark chapel cavity behind the sternum and faint cyan signal, candlelit practical effects, heavy grain, no text."),
    record("Macro photography, sleep observation", "Private residence under observation", "July 18, 2024", "The palm contains a miniature door that opens only while the owner is asleep. Behind it is a room with a chair facing the bed.", "Dust from the miniature threshold matches the plaster in the house's attic, although the attic has no door.", "Analog horror film still of an open palm containing a tiny wooden door ringed with teeth on stained altar cloth, wax and rotting fabric, no text."),
    record("Dermatological mapping, directional video", "Dermatology ward, location withheld", "August 4, 2024", "A healed incision redraws itself whenever the patient changes direction. The line work resembles a floor plan that refuses to close.", "The map includes a room labeled with the patient's name, but no room exists in the patient's home.", "Lost clinical analog horror still of skin marked with a glowing architectural floor plan, candlelight, muted desaturated burgundy brown green, film grain, no text."),
    record("Clinical portraiture, voice comparison", "Observation room at a private hospital", "September 11, 2024", "It speaks only in the voice of someone the patient has not met yet. The second mouth opens when the room falls silent.", "The voice was identified as a future archivist. The archivist denies having spoken the recording.", "Dark practical-effects horror film still of a shoulder with a small second mouth and irregular teeth, old wallpaper, candlelight, soft focus, no text."),
    record("Radiograph series, skeletal alignment study", "University imaging archive", "October 1, 2024", "The radiograph shows another frame standing several centimetres behind the first. Both skeletons turn their heads toward the same sound.", "A repeat scan showed the second skeleton had moved closer to the patient's spine.", "Analog film still of an X-ray with two overlapping skeletons, second frame standing behind the first, candles in a clinical room, heavy grain, no text."),
    record("Preserved tissue sample, reaction log", "Cold storage cabinet 4B", "November 19, 2024", "A removed organ continues to react to rooms it has never occupied. It contracts whenever a door is opened nearby.", "The jar is labeled with an address that belongs to a house demolished before the sample was collected.", "Lost horror film still of a preserved organ in cloudy glass casting a room-shaped shadow on an archive shelf, wax, rust, candlelight, no text."),
    record("Acoustic dermatology, weather log", "Veilhouse medical annex", "December 22, 2024", "Rain is heard beneath the epidermis whenever the house is about to change. The sound begins in the left forearm and travels inward.", "The skin remains dry. The audio contains distant thunder and a door closing underwater.", "Analog horror film still of a forearm with a tiny storm and corridor visible under the skin, wet tactile surface, candle and cyan glow, no text."),
  ],
  "weirdcore": [
    record("Nursery photography, sleep diary", "Childhood bedroom reconstructed from memory", "January 5, 2024", "The moon in the nursery has learned the names of everyone who sleeps there. It rises slightly whenever a name is spoken aloud.", "No window faces the moon. The wallpaper contains a second, smaller room behind the stars.", "Lost analog horror film still of an oversized pastel nursery with a moon inside the wallpaper, bed facing camera, hidden mouth in ceiling, faded grain, no text."),
    record("Party-room stills, guest register", "Birthday room in a condemned family home", "February 20, 2024", "Every balloon bears the face of a guest who has not yet arrived. The faces turn toward the doorway at the sound of footsteps.", "The guest register includes one name written in wax beneath the table.", "Weirdcore analog horror still of a faded birthday room with balloons reflecting absent faces, one extra chair and shrine, muted burgundy ochre black green, no text."),
    record("Carpet sample, horizon survey", "Nursery wing of a closed school", "March 15, 2024", "The pattern ends at a line where the room continues into weather. Wind crosses the line without disturbing the carpet.", "A child-sized footprint begins on the carpet and ends in rain that no camera records.", "Lost 1980s horror still of a pastel carpet ending at a horizon with dark weather beyond, tiny footprints, candlelight, heavy film grain, no text."),
    record("VHS transfer, family footage index", "Television found beneath a bed", "April 9, 2024", "It plays family footage from houses the viewer has never lived in. Each recording ends with the camera placed under the same bed.", "The television has no antenna. Its screen is warm even when unplugged.", "Analog horror film still of a small television beneath a child's bed showing an impossible family dinner, wet cables, porcelain saint, no text."),
    record("Plastic fruit, audio assay", "Indoor playroom with sealed windows", "May 27, 2024", "The fruit is hollow, warm, and full of tiny recorded voices. The voices stop when the fruit is held near a mirror.", "One recording contains the sound of a room being built around the listener.", "Lost practical-effects horror still of a plastic orchard of pale hollow fruit with teeth inside one split fruit, child's coat, faded film, no text."),
    record("Hallway photography, length comparison", "Pastel corridor behind a closed nursery", "June 30, 2024", "A cheerful corridor becomes longer whenever someone says they feel safe. The colors fade one shade at a time toward the far end.", "The corridor's exit sign points toward the room it is meant to lead away from.", "Analog horror film still of an impossibly long cheerful pastel hallway, one candle at the vanishing point, muted burgundy brown sickly green, no text."),
    record("Child's drawing, paper architecture", "Recovered from a school archive", "July 22, 2024", "A child's house plan adds a window each time the paper is folded. The new windows show rooms from the observer's home.", "The paper is thicker after every fold, as if another wall has been added inside it.", "Dark surreal film still of a child's house drawing with a real window opening from the paper, wax and tiny teeth, candlelit table, no text."),
    record("Textile sample, handle observation", "Soft-play room sealed after inspection", "August 18, 2024", "It feels like a blanket until the handle begins turning from the other side. The fabric keeps the warmth of whoever last touched it.", "No hinge or latch exists behind the door. The handle turns at the exact moment the room is empty.", "Lost analog horror still of a quilted bedroom door with handle turning from the other side, pale cyan under the threshold, heavy grain, no text."),
  ],
  "grotesque-architecture": [
    record("Rooftop photography, window census", "Old city district photographed at dusk", "September 6, 2023", "A city watches from its roofline and counts the windows left open. The gargoyles change position between exposures.", "The census total increases whenever a resident closes a curtain.", "Analog horror film still of a roofline crowded with gargoyles pointing toward lit windows, one window like an eye, muted burgundy brown black green, no text."),
    record("Architectural vibration study", "Cathedral nave beneath renovation scaffolding", "October 19, 2023", "Its arches expand and contract around a heart no architect can locate. Mortar dust falls in time with the pulse.", "The building's pulse stops when the nave is empty, then resumes when a witness enters.", "Lost horror film still of a cathedral nave with rib-like arches around a hidden pulsing heart, candles as surgical markers, wet stone, heavy grain, no text."),
    record("Floor-plan survey, tenant interviews", "Apartment block scheduled for expansion", "November 28, 2023", "Residents wake to find a new level above them, furnished in their own style. The new level has no stairs from below.", "Every new room contains a chair facing the door and a damp copy of the resident's key.", "Analog horror film still of an apartment building with a new floor grown above it, windows holding copied chairs, roots and cables, no text."),
    record("Pipe resonance recordings, maintenance log", "Stairwell of a municipal housing block", "December 21, 2023", "The pipes hum in a sequence that resembles a diagnosis. The diagnosis changes after every repair.", "The maintenance crew found a rib-shaped valve behind the plaster and sealed it with altar wax.", "Lost film still of a narrow stairwell with organ-like pipes and a small altar halfway up, wet stone, rust, candlelight, no text."),
    record("Facade layers, plaster microscopy", "Commercial building under demolition", "January 26, 2024", "Removing one layer of plaster reveals a second building looking outward. Its windows are smaller but perfectly aligned with the original.", "The inner facade has a front door. The demolition crew refuses to document where it opens.", "Analog horror still of a building facade peeled back to reveal a smaller building staring outward, wet plaster like skin, candlelit windows, no text."),
    record("Bridge survey, daily displacement log", "Footbridge over a drained canal", "February 9, 2024", "Each morning the bridge has shifted a few inches toward the people crossing it. The riverbed beneath it shows footprints facing upstream.", "The bridge is bolted to bedrock. The bolts move with the structure and remain cold to the touch.", "Lost analog horror film still of a bridge leaning toward silent walkers, underside threaded with veins and rusted cables, muted colors, no text."),
    record("Thermal mapping, room inventory", "House abandoned after a winter fire", "March 31, 2024", "Rain falls only in the room where the previous owner used to sleep. The rain never reaches the floor.", "The room's ceiling is dry. A weather report taped inside the closet predicts rain for the rest of the house.", "Analog horror film still of a house with one interior weather room raining over an old bed, organic walls, rotting fabric, sickly green shadows, no text."),
    record("Wallpaper removal, miniature survey", "Row house awaiting restoration", "April 24, 2024", "A miniature skyline grows behind the wallpaper whenever the lights go out. Its windows imitate the lights in the neighboring homes.", "The skyline has acquired one tower that does not exist in the city outside.", "Lost horror film still of a miniature city growing behind torn wallpaper, tiny lit windows and crooked towers, one eye in plaster, heavy grain, no text."),
  ],
  "cult-horror": [
    record("Room photography, heat-map survey", "Basement meeting room beneath a closed lodge", "May 12, 2023", "No ceremony without a witness. No witness leaves unchanged. The room warms before anyone enters.", "A chair is always damp with condensation, even after being removed from the building.", "Analog horror film still of an empty ritual room with one warm wooden chair, wet footprints and candles, decaying basement, muted burgundy brown black green, no text."),
    record("Thread diagram, membership ledger", "Meeting hall behind a shuttered textile mill", "June 1, 2023", "Every member is connected to a name that has not yet been spoken. The thread tightens whenever someone leaves the room.", "The final name in the ledger is the name of whoever is currently reading it.", "Lost analog horror film still of red thread connecting blank silhouettes and disappearing into a mouth-shaped wall crack, wax and candles, no text."),
    record("Porcelain mask, mirror comparison", "Storage room of an unnamed society", "July 7, 2023", "It fits whoever wears it, but the reflection belongs to the missing member. The mask is warm on the inside.", "After the mask was boxed, a reflection continued to appear on the box glass.", "Dark practical-effects horror still of a blank porcelain mask hanging in a meeting room, reflection showing an absent person, candlelight, no text."),
    record("Table survey, thermal chair study", "Dining room of an abandoned rectory", "August 16, 2023", "The extra chair is always warm before the meeting begins. No one admits to placing it at the table.", "The chair's wood contains fingerprints beneath the varnish, all facing inward.", "Analog horror film still of a long ritual table with one wet warm extra chair, a gold tooth on a plate, silhouettes behind curtain, no text."),
    record("Hymnbook, group audio recording", "Chapel with no registered congregation", "September 25, 2023", "The group learned it together, though no one remembers teaching it. The melody continues when the room is empty.", "The hymn has no composer, but its final note matches the sound of a door locking.", "Lost analog horror film still of a hymnbook open on a pulpit, pages turning toward a mouth in the wall, candles, wet paper, no text."),
    record("Door fragment, accession photograph", "Behind the catalogue wall of a private archive", "October 13, 2023", "An accession without an address, found behind the catalogue itself. The door opens only when the catalogue is closed.", "Every attempt to number the door adds a new door behind it.", "Dark analog horror film still of a door behind another door in a ruined hall, ritual ledger nailed to inner door, candles and wet footprints, no text."),
    record("Witness ledger, ink analysis", "Stone altar recovered from a coastal meeting site", "November 30, 2023", "Names disappear from the list after the person signs beside them. The ink remains wet for exactly one hour.", "The missing names reappear on the attendance sheet of the following meeting.", "Lost film still of a witness ledger on a stone altar, names fading as a pale hand signs, wax and rust, muted burgundy brown black green, no text."),
    record("Tidal survey, circle photography", "Shoreline revealed during an extreme low tide", "December 29, 2023", "The water recedes to reveal a circle that was waiting under the shore. Hooded figures arrive before the tide has finished leaving.", "The circle remains dry when the sea returns, and the water around it is warmer than the air.", "Analog horror film still of a ritual circle revealed beneath low tide, hooded silhouettes and candles on wet stone, rotting fabric, heavy grain, no text."),
  ],
};
