export type ArchiveMetadata = {
  id: string;
  title: string;
  medium: string;
  location: string;
  accessionDate: string;
  description: string;
  curatorNote: string;
  prompt: string;
};

const sharedStyle = "Original dark surreal horror image, obscure underground analog horror film, grotesque body horror, decaying religious imagery, organic architecture, ritualistic symbolism, dreamlike psychological unease, wet fleshy textures, teeth, bone-like forms, rotting fabric, wax, rust, handmade practical-effects materials, lost 1970s or 1980s experimental horror movie frame, muted burgundy, brown, dirty ochre, black and sickly green, dim candlelight, weak cyan television glow, deep shadows, soft focus, heavy film grain, faded colors, slight lens distortion, dark vignette, aged analog-film texture, tactile oppressive mysterious cinematic physical horror-film set, no text.";

const record = (id: string, title: string, medium: string, location: string, accessionDate: string, description: string, curatorNote: string, scene: string): ArchiveMetadata => ({
  id, title, medium, location, accessionDate, description, curatorNote, prompt: `${sharedStyle} Subject and composition: ${scene}`,
});

export const archiveMetadata: Record<string, ArchiveMetadata[]> = {
  "body-horror": [
    record("BH-001", "The Molting Mannequin", "16mm film transfer, practical silicone and wax effects", "Abandoned theatrical workshop, Berlin", "October 12, 2023", "A dressmaker’s mannequin stands in a dim room while canvas skin peels away in wet strips. Beneath the rotting fabric is pulsing muscle and exposed rusted wire; its half-sloughed face reveals a jaw made entirely of tightly packed human teeth clicking in a mechanical chewing rhythm.", "The film degrades at the 14-second mark. Audio analysis detects wet tearing and low rhythmic breathing that does not match the frame rate.", "A full-body dressmaker mannequin shedding wet canvas skin in a ruined theatrical workshop, exposed muscle and rusted wire, tooth-filled jaw, locked-off 16mm camera composition."),
    record("BH-002", "Graft Ward 4", "Polaroid series, medical chart documentation", "Deconstructed hospital wing, rural Ohio", "February 2, 2024", "A hospital bed holds a patient formed from at least four human torsos grafted together at the ribs with black sutures resembling rusted barbed wire. IV bags contain thick yellow wax; the central face sleeps while three faces embedded in the chest and shoulders watch the camera.", "The medical chart lists the blood type as ‘O-Negative / Rust.’ The hospital cannot be located on any modern map.", "A decayed hospital bed with four grafted torsos, black barbed-wire sutures, wax-filled IV bags and three awake faces staring at the camera, Polaroid flash."),
    record("BH-003", "The Jawline Expansion", "VHS capture, analog video synthesis", "Unknown basement studio", "May 18, 2024", "A profile face has unhinged and multiplied: three lower jaws hang from the skull on wet sinew. Bone-and-rust teeth fill each mouth while stretched translucent neck skin reveals pulsing arteries. Tape tracking makes the mouths widen with every frame.", "The subject never blinks. The audio is grinding teeth and distant muffled weeping.", "Extreme side-profile close-up of a face with three suspended lower jaws, wet sinew, bone-and-rust teeth, translucent neck and VHS tracking distortion in a basement studio."),
    record("BH-004", "Subdermal Architecture", "X-ray imaging, photographic overlay", "Private clinic shut down by authorities", "August 30, 2024", "An X-ray shows ribs restructured into pointed Gothic arches and the spine twisted into a spiral staircase. Lungs fill the nave as dark caverns; an overlaid image of the patient’s back shows skin stretched over bone and weeping clear viscous fluid.", "The patient felt ‘hollowed out’ and ‘echoing.’ Contact with the clinic was lost. The X-ray film is warm to the touch.", "Clinical X-ray and photographic overlay of a torso whose ribs form a Gothic cathedral, spine as spiral staircase, lungs as hollow nave, skin stretched and glistening."),
  ],
  "technology-nightmares": [
    record("TN-001", "CRT Monitor 88-B", "8mm film, practical electronics modification", "Electronics repair shop, Tokyo, closed 1998", "November 4, 2023", "A bulky beige 1980s CRT monitor has lost its glass screen; a massive wet blinking eye occupies the opening, its iris a swirl of dead pixels and rust. Black cables pulse dark fluid into the wall socket and oily wax sweats from the casing.", "The cables bled when unplugged. The eye continued blinking, so the monitor was plugged back in.", "Beige 1980s CRT monitor on a rusted desk with a wet blinking eye instead of glass, pulsing black cables, oily wax and dim repair-shop darkness."),
    record("TN-002", "The Switchboard Operator", "Audio recording, photographic documentation", "Abandoned telephone exchange, London", "January 15, 2024", "A rusted rotary telephone rests on rotting fabric. Its earpiece is a human ear fused to metal with copper wire through the lobe; its mouthpiece is a cracked wet mouth that inhales when the phone rings.", "The number written on the base answered in the investigators’ own voice, reading back their current coordinates.", "Macro view of a rusted rotary telephone with a human ear receiver and small wet mouth mouthpiece, copper wire, rotting fabric and black exchange-room shadows."),
    record("TN-003", "VHS Degradation Sequence", "VHS tape, analog glitch art", "Found in a thrift store, Portland", "April 22, 2024", "A birthday-party home video degrades as its people melt into magnetic tracking lines. Faces stretch into wet ribbons of flesh and static, the cake becomes pulsing wax and teeth, and children turn toward the camera with static-filled eyes while the audio becomes guttural chanting.", "The tape has been viewed 47 times. Each time, the children are closer to the camera. It is locked in a lead box.", "A decaying VHS birthday party frozen mid-glitch: children with static eyes, cake transformed into wax and teeth, bodies dissolving into horizontal magnetic tracking lines, dark living-room set."),
    record("TN-004", "Server Room 04", "Digital photography, thermal imaging", "Data center basement, Seattle", "July 9, 2024", "Rusting server racks fill a dark room. Cooling fans have become pink wet human lungs, ethernet bundles pulse like arteries pumping blue fluid, and the floor is covered in rotting fabric and shed skin. Thermal imaging reads exactly 98.6°F.", "The data center was decommissioned in 2012. The servers still process data, but the calculation is unknown.", "Low-angle server-room photograph with racks fitted with breathing human lungs, pulsing blue-fluid artery cables, shed skin on the floor and cyan thermal glow."),
  ],
  "liminal-spaces": [
    record("LS-001", "The Endless Hotel Corridor", "35mm film, practical set design", "Unknown hotel, Nevada", "March 3, 2024", "A 1970s floral hotel corridor has wallpaper peeling in wet strips to reveal dark pulsing muscle. The soaked carpet squelches; doors open onto darkness, while a figure in a rotting bathrobe faces the far wall and never turns.", "The corridor was walked for two hours without reaching its end. The carpet remains wet.", "Deep perspective 1970s hotel corridor with peeling floral wallpaper revealing muscle, wet carpet, half-open black doors and a distant bathrobe figure facing the wall."),
    record("LS-002", "Indoor Pool at 3 AM", "Polaroid, audio capture", "Community center, suburban Midwest", "May 12, 2024", "An empty tiled pool contains thick opaque water the color of bruised flesh. A diving board is made from fused yellowed human bones lashed with rusted wire. The surface is still, but audio records rhythmic splashing from the deep end.", "The water contains high salt, iron and an unknown organic compound. Entry is prohibited.", "Empty tiled indoor pool at 3 AM, bruised-flesh water perfectly still, bone diving board lashed with rusted wire, flickering fluorescent lights and long shadows."),
    record("LS-003", "The Backrooms of the Flesh", "VHS screenshot, digital manipulation", "The ‘Yellow Rooms’", "August 18, 2024", "An endless damp yellow room has fluorescent ceiling lights replaced by glowing rows of human teeth. The spongy floor yields and weeps clear fluid; distant walls breathe while a researcher’s footsteps continue on the audio feed.", "Three researchers entered. Two returned. The third is still walking.", "Endless damp yellow corridor with rows of glowing teeth as ceiling lights, yielding wet floor, breathing walls and a tiny distant human silhouette, degraded VHS frame."),
    record("LS-004", "Empty Mall Food Court", "16mm film, practical effects", "Abandoned shopping mall, Ohio", "October 31, 2024", "A dead 1990s mall food court holds mannequins with smooth wax faces and vertical mouth slits. A dry fountain is filled with thousands of human teeth; the mannequins turn their heads when the camera pans away.", "The mall closed in 1998. The mannequins were never part of the original decor.", "Abandoned 1990s mall food court with wax-faced mannequins at plastic tables, vertical mouths, dead neon and a dry fountain filled with teeth, 16mm grain."),
  ],
  "weirdcore": [
    record("WC-001", "Playground at Dusk", "Digital photograph, heavy compression artifacts", "Local park, location redacted", "February 14, 2024", "A rusty swing set silhouettes against a sky of black-and-white television static. Swings are strips of rotting fabric and matted hair; an oversized moon hangs low, pockmarked and weeping dark fluid, while wet eyes flash from the bushes.", "The park was demolished in 2010, yet the photograph was taken in 2024. The static emits a low 60Hz hum.", "Rusty playground at dusk under a television-static sky, swings made of hair and rotting fabric, oversized weeping moon and two wet eyes in bushes, compressed digital photograph."),
    record("WC-002", "Birthday Party, 1998", "VHS capture, analog glitch", "Private residence", "June 6, 2024", "A blurry birthday video shows children around a table and a cake made of pulsing pink wax and embedded teeth with bone candles. The children chant coordinates; when the central child blows out the candles, the room goes black.", "Enhanced audio confirms the song is not ‘Happy Birthday.’ It is a coordinate sequence.", "Low-resolution VHS birthday party with artifact-obscured children, wax-and-teeth cake with bone candles, sickly flash and the room falling into blackness."),
    record("WC-003", "The Family Portrait", "Polaroid, chemical alteration", "Attic of an abandoned house", "September 9, 2024", "A smiling 1980s family portrait shows smiles stretched too wide, peeling wallpaper-like skin, wet red muscle, and black eyes reflecting a different room. The background is an impossible void.", "The photograph contains human blood and rust. The family disappeared in 1987.", "Chemical-distorted Polaroid family portrait, faces smiling too widely with peeling skin and muscle beneath, black reflective eyes and impossible void background."),
    record("WC-004", "Bedroom Nightlight", "8mm film, practical lighting effects", "Child’s bedroom, suburban home", "November 11, 2024", "A star-shaped nightlight casts shadows of elongated hands reaching toward a bed. The mattress breathes, the sheets resemble dried skin, and wet blinking eyes shine from beneath it.", "The child is now an adult and refuses darkness. The hands are reportedly closer each year.", "Child’s bedroom at night lit by a star nightlight, elongated hand shadows reaching over a breathing bed, dried-skin sheets and wet eyes beneath, 8mm practical effects."),
  ],
  "grotesque-architecture": [
    record("GA-001", "The Breathing Apartment Block", "Drone footage, thermal imaging", "Brutalist housing estate, Eastern Europe", "April 4, 2024", "A brutalist apartment block sweats dark fluid. Its windows are blinking eyes, balconies are rib-like structures pulsing with a heartbeat, and the entrance is a wet mouth whose doors grind like teeth.", "Built in 1974, the eyes appeared in 2023. Residents hear the building whisper at night.", "Aerial view of a brutalist apartment block with blinking eye windows, rib balconies, sweating concrete and a massive wet mouth entrance, thermal haze."),
    record("GA-002", "Cathedral of the Marrow", "35mm photography, practical set design", "Unknown forest, Pacific Northwest", "July 21, 2024", "A Gothic cathedral is assembled from giant yellowed human bones lashed with black sinew. Stained-glass windows are dyed stretched skin; a pulsing heart hangs as the altar over wet red moss.", "The cathedral is absent from every map. DNA testing confirms the bones are human. Avoid sermon hours.", "Bone-built Gothic cathedral in a dark forest, femur arches lashed with sinew, stained skin windows, suspended heart altar and wet red moss, 35mm photograph."),
    record("GA-003", "The Subway Station That Swallows", "Security camera footage, analog video", "Abandoned subway station, New York City", "October 10, 2024", "White tooth tiles line a subway platform and weep clear fluid. The tracks form a digestive tract with bone rails; a segmented flesh train arrives on tiny clicking legs and opens onto a wet interior.", "The station closed in 1980. The train arrives every 13 minutes, destination unknown.", "Abandoned subway platform tiled in teeth, digestive-tract tracks and a segmented fleshy train with tiny legs opening its dark wet doors, security-camera angle."),
    record("GA-004", "Skyscraper 404", "Digital photography, long exposure", "Financial district, major metropolis", "December 12, 2024", "A glass-and-steel skyscraper bleeds rust, weeps black fluid, leans under unseen weight, and grows upward. Its antenna is a rusted spine topped by a red scanning eye.", "The tower grew from 40 to 44 stories since 2020. Tenants have not noticed and blueprints remain unchanged.", "Long-exposure financial district image of a growing glass skyscraper with blood-rusted beams, black window tears, spine antenna and blinking red eye."),
  ],
  "cult-horror": [
    record("CH-001", "The Basement Ritual", "16mm film, practical lighting effects", "Suburban basement, Midwest", "January 1, 2024", "Five robed figures circle an altar made of fused breathing bodies with faces pressed together. Candles of rendered fat burn sickly green; the figures’ mouths are sewn shut, yet chanting comes from the walls.", "The figures are a missing family of five reported in 1992. They have not aged.", "Dim basement ritual with five robed figures around a fused breathing-body altar, green fat candles, sewn mouths and chanting walls, 16mm practical-effects frame."),
    record("CH-002", "The Chanting Circle", "Aerial drone photography, thermal imaging", "Deep forest, Pacific Northwest", "March 15, 2024", "Twelve pale figures stand in a pentagram of blood and rust. Scarified symbols glow in thermal imaging; their shadows point inward toward a depression where something massive breathes beneath the soil.", "The clearing is absent from satellite imagery. After a 13-minute signal loss, every figure looked directly at the drone.", "Aerial night view of a forest clearing with twelve scarified figures in a blood-and-rust pentagram, inward shadows and breathing earth depression, thermal highlights."),
    record("CH-003", "The Initiation", "Polaroid, macro photography", "Unknown location", "May 5, 2024", "A terrified face is branded by a live writhing black worm held in a rotting leather glove. The mark burrows into the forehead; blistered skin reveals muscle and the open mouth holds black-stained teeth.", "The subject is a missing college student. The same brand appears in three other cult disappearances.", "Harsh macro Polaroid of a terrified face and gloved hand pressing a live black worm brand into the forehead, peeling skin, wet muscle and black-stained teeth."),
    record("CH-004", "The Communion of the Blind", "8mm film, practical effects", "Abandoned church, rural Italy", "August 8, 2024", "Twenty blindfolded, black-thread-sewn figures sit in a rotting church while a rusted-mask celebrant serves wet clay mixed with teeth and nails. The congregation eats in mechanical rhythm to the sound of crunching bone.", "The deconsecrated church fills every Sunday at 3:33 AM. The congregation does not respond; it only eats.", "Rotting rural church with twenty formally dressed blind figures eating tooth-and-nail clay from a silver platter, rusted-mask celebrant, green candlelight and 8mm grain."),
  ],
};

export default archiveMetadata;
