import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { useRoute } from "wouter";
import { PageShell, images } from "./ContentPageShell";

const dispatchDetail = {
  "003": { eyebrow: "DISPATCH 003 / DEEP DIVE", title: "The Anatomy Of Ruin", image: images[3], paragraphs: ["This week, Body Horror specimen BH-04 generated 847 new resident testimonies. Three claim to have visited the building site in their dreams. One claims to have woken with new scars. The house does not confirm or deny.", "The body is always under construction. In the recovered images, the ruin is not a place the body enters; it is a process the body performs. Bricks remember pressure. Stairwells develop a pulse. Windows become organs for looking inward.", "Read the specimen slowly. The first room is architectural. The second is anatomical. By the third, the distinction has begun to fail."] },
  "002": { eyebrow: "DISPATCH 002 / CONTRIBUTOR FILE", title: "The Rooms We Carry", image: images[7], paragraphs: ["We spoke with a maker who photographs empty rooms until they begin to remember the people who left them. Their practice begins with absence but ends with a kind of weather.", "Every room is a witness with poor recall. The work asks what remains when furniture, family, and function are removed, leaving only the pressure of a life in the walls."] },
  "001": { eyebrow: "DISPATCH 001 / ANNOUNCEMENT", title: "The First Door Opens", image: images[0], paragraphs: ["The archive is open. Seven doors are marked. The first field notes have been recovered from behind the wallpaper.", "Enter without expecting a map. The house has kept its own index, and it does not always agree with ours."] },
};
const noteDetail = {
  "field-note-017:-ward-07": { eyebrow: "CURATOR'S JOURNAL / FIELD NOTE 017", title: "Ward 07 Has No Outside", image: images[2], text: "Nurse J. Morrison reported on 03/14/2024: ‘The corridor measured 47 meters on Monday. Today it measures 63 meters. We have not added space. The walls are breathing. Patients are reporting that their rooms move when they are not looking. Room 714 is now where 712 used to be. I am afraid to go to sleep.’\n\nCurator's annotation: The house confirms. Ward 07 has no outside. Do not attempt to find the end of the corridor." },
  "statement-from-room-714": { eyebrow: "RESIDENT TESTIMONY / ROOM 714", title: "The Hallway Was Inside My Room", image: images[4], text: "I woke because someone was moving furniture in the hallway. When I opened the door, the hallway was inside my room. I could see the bed from both sides. I have not slept there since, but every morning the pillow is warm.\n\nThe witness requested that the room number be removed. The room declined." },
  "plan:-the-unfinished-stair": { eyebrow: "ARCHITECT'S BLUEPRINT / PLATE 04", title: "The Unfinished Stair", image: images[5], text: "The stair rises through three floors and returns to its own underside. Annotation in red pencil: do not measure the distance between landings while standing on a landing.\n\nA second hand has added a note near the lowest step: ‘The building is not supporting the stair. The stair is supporting the building.’" },
  "case-04:-the-listening-body": { eyebrow: "MEDICAL REPORT / CASE 04", title: "The Listening Body", image: images[3], text: "Patient presents with an additional cavity behind the sternum. The cavity produces a low signal when addressed by name. Patient insists the sound is not inside them; it is waiting for them inside the room.\n\nRecommendation: do not leave the patient alone with an unmarked door. Do not answer the signal after midnight." },
  "found-between-pages-18-and-19": { eyebrow: "RECOVERED MARGIN NOTE / UNNUMBERED", title: "Who Is Doing The Counting?", image: images[7], text: "The house is not empty.\nThe house is not full.\nThe difference is who is doing the counting.\n\nThe paper was warm when recovered. No source of heat was found in the archive room." },
};

export default function DocumentDetail() {
  const [, dispatchParams] = useRoute("/dispatches/:id");
  const [, noteParams] = useRoute("/field-notes/:slug");
  const detail = dispatchParams?.id ? dispatchDetail[dispatchParams.id as keyof typeof dispatchDetail] : undefined;
  const note = noteParams?.slug ? noteDetail[noteParams.slug as keyof typeof noteDetail] : undefined;
  if (note) return <PageShell eyebrow={note.eyebrow} title={<>{note.title}<br /><em>recovered in the margin.</em></>} intro="A document from the Field Notes library, opened for close reading."><article className="document-detail"><img className="document-hero hover-enlarge" src={note.image} alt="" /><p>{note.text}</p><a className="button-outline" href="/field-notes"><ArrowLeft size={15} /> Return to the library</a></article></PageShell>;
  if (!detail) return <PageShell eyebrow="DOCUMENT NOT FOUND" title={<>The room is<br /><em>unlisted.</em></>} intro="This transmission has not yet been filed in the public ledger."><a className="button-outline" href="/dispatches"><ArrowLeft size={15} /> Return to dispatches</a></PageShell>;
  return <PageShell eyebrow={detail.eyebrow} title={<>{detail.title}<br /><em>transmission open.</em></>} intro="A dispatch from inside the living archive."><article className="document-detail"><img className="document-hero hover-enlarge" src={detail.image} alt="" />{detail.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<a className="button-outline" href="/dispatches"><ArrowLeft size={15} /> Return to dispatches <ArrowUpRight size={15} /></a></article></PageShell>;
}
